# This file was generated by GoReleaser. DO NOT EDIT.
cask "tessera" do
  version "0.51.0"

  on_macos do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/tessera--v#{version}--darwin-amd64.tar.gz"
      sha256 "b78ae41969caec7c0c0a869b2b79b61c2c24850b36e5df44b8778a26f3845960"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/tessera--v#{version}--darwin-arm64.tar.gz"
      sha256 "7f08a8e57e571d260b95aecc7e9198d6b54d7368d062fe4cfe4585c240bd72a0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/tessera--v#{version}--linux-amd64.tar.gz"
      sha256 "a2fa4407711a6d2b0103663a9ef47b0f0a7a6031a3ec1b9f7eb8aa55e86a1133"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/tessera--v#{version}--linux-arm64.tar.gz"
      sha256 "a804880eee2494b57dbc57e67056cd5d593a6ed8fad8801122801cc5d68cfe46"
    end
  end

  name "tessera"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tessera"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tessera"]
    end
  end

  # No zap stanza required

end
