# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtfutil" do
  version "0.51.0"

  on_macos do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/wtf_#{version}_darwin_amd64.tar.gz"
      sha256 "cc585394586b532ad7fa7b5b1115aa6f932c0632b1acfbeb36fded6bb27a3b21"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/wtf_#{version}_darwin_arm64.tar.gz"
      sha256 "96d69fe929dcbe1a409f506cd730bcc36ddd2d6d0b73dcad2142edea8c92c6a3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/wtf_#{version}_linux_amd64.tar.gz"
      sha256 "5b1670e8a6a2bfcddf699bccbaae6b53263d75b87ef099d8e2a837c1d5ffc81b"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/wtf_#{version}_linux_arm64.tar.gz"
      sha256 "125ffb623e610dfc8076034b57cf0c13e8422b52924177ce752c541c6e356203"
    end
  end

  name "wtfutil"
  desc "The personal information dashboard for your terminal."
  homepage "https://wtfutil.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtfutil"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtfutil"]
    end
  end

  # No zap stanza required

end
