# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtfutil" do
  name "wtfutil"
  desc "The personal information dashboard for your terminal."
  homepage "https://wtfutil.com"
  version "0.48.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtfutil"

  on_macos do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/wtf_#{version}_darwin_amd64.tar.gz"
      sha256 "237adfe9d93eb1e3d50de15ce7bfcfb5d7cc7695fd76b72b08dbb37bb43dae96"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/wtf_#{version}_darwin_arm64.tar.gz"
      sha256 "7818d19988e2bba0c12cb6c5ad3f434803747065346ee92c097e467eb55b74f3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/wtf_#{version}_linux_amd64.tar.gz"
      sha256 "113e229af6e33d95aac39892daa553214cb205c2fba5ceaf5eaa5f728bce0a3e"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/wtf_#{version}_linux_arm64.tar.gz"
      sha256 "aabde0f8879049f026da5785a7b5de3b0069e7ac94d9485de448b835b6420a3d"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtfutil"]
    end
  end

  # No zap stanza required
end
