# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtfutil" do
  name "wtfutil"
  desc "The personal information dashboard for your terminal."
  homepage "https://wtfutil.com"
  version "0.49.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtfutil"

  on_macos do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/wtf_#{version}_darwin_amd64.tar.gz"
      sha256 "f3a3ddce7b42a759394bb3c1d6538ef48f8c1ec1b4497e6c5efaadfdf2de1f00"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/wtf_#{version}_darwin_arm64.tar.gz"
      sha256 "39a9fe7b005442c9fd813cf4f16acb0408516677919ec10d32b78082967213db"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/wtf_#{version}_linux_amd64.tar.gz"
      sha256 "b29cabf18b4a7357daebbb5418e40c506564dbcdf94ee7846879cf3442333193"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v#{version}/wtf_#{version}_linux_arm64.tar.gz"
      sha256 "0b6e578a5f3aefaca99576f4ee80376657b678a8bcdda30929e52edd6db587ba"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtfutil"]
    end
  end

  # No zap stanza required
end
